name: Build Python Script with PyInstaller

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-latest, macos-14, macos-13]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.7'

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          if [[ "${{ matrix.os }}" == "macos-14" ]]; then
            # On macOS M1
            export ARCHFLAGS="-arch x86_64 -arch arm64"
          elif [[ "${{ matrix.os }}" == "macos-13" ]]; then
            # On macOS with intel cpus
            export ARCHFLAGS="-arch x86_64"
          fi
          # install a working numpy to avoid issues with numpy 2.0
          pip install numpy==1.25.0
          pip install pyperclip
          pip install pyinstaller
          pip install moviepy

      - name: Compile script with PyInstaller
        shell: bash
        run: |
          # Create hook file for Tkinter
          echo "from PyInstaller.utils.hooks import collect_data_files" > hook-tkinter.py
          echo "datas = collect_data_files('tkinter')" >> hook-tkinter.py
          
          if [[ "${{ matrix.os }}" == "macos-14" ]]; then
            # Build Apple Silicon binary
            pyinstaller --onedir --windowed --name FileSizeTreeChecker-arm64 FileSizeTreeChecker.py \
              --target-architecture arm64 \
              --add-binary='/System/Library/Frameworks/Tk.framework/Tk':'tk' \
              --add-binary='/System/Library/Frameworks/Tcl.framework/Tcl':'tcl' \
              --hidden-import='tkinter' \
              --clean
          elif [[ "${{ matrix.os }}" == "macos-13" ]]; then
            # Build Intel binary
            pyinstaller --onedir --windowed --name FileSizeTreeChecker-intel FileSizeTreeChecker.py \
              --target-architecture x86_64 \
              --add-binary='/System/Library/Frameworks/Tk.framework/Tk':'tk' \
              --add-binary='/System/Library/Frameworks/Tcl.framework/Tcl':'tcl' \
              --hidden-import='tkinter' \
              --clean
          else
            # On other platforms, use default architecture
            pyinstaller --onedir --windowed --name FileSizeTreeChecker FileSizeTreeChecker.py \
              --hidden-import='tkinter' \
              --clean
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: FileSizeTreeChecker-${{ matrix.os }}  # Unique name per OS
          path: dist/
