name: Build Python Script with PyInstaller

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]  # Add all OSes
    runs-on: ${{ matrix.os }}  # Use the matrix OS

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.7'

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          # install a working numpy to avoid issues with numpy 2.0
          if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            # On macOS, install universal2 versions of dependencies
            export ARCHFLAGS="-arch x86_64 -arch arm64"
            pip install numpy==1.25.0
            pip install pyinstaller
            pip install moviepy --no-binary :all:
            pip install pyperclip
          else
            pip install numpy==1.25.0
            pip install pyinstaller
            pip install moviepy
            pip install pyperclip
          fi

      - name: Compile script with PyInstaller
        shell: bash
        run: |
          if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            # Build Intel binary
            pyinstaller --onefile --name FileSizeTreeChecker-intel FileSizeTreeChecker.py --argv-emulation --optimize 2 --target-architecture x86_64 --clean
            
            # Build Apple Silicon binary
            # pyinstaller --onefile --name FileSizeTreeChecker-arm64 FileSizeTreeChecker.py --argv-emulation --optimize 2 --target-architecture arm64 --clean
          else
            # On other platforms, use default architecture
            pyinstaller --onefile --name FileSizeTreeChecker FileSizeTreeChecker.py --argv-emulation --optimize 2 --clean
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: compiled-binary-${{ matrix.os }}  # Unique name per OS
          path: dist/
